import os
import subprocess
import sys
from datetime import datetime

ASM_FILE = "xbios.asm"
BIN_FILE = "xbios.rom"
HEADER_FILE = "xbios_rom.h"
ARRAY_NAME = "copico_xbios_bin"

# Relative to this script: bios/ -> master-hat-firmware/ -> firmware/ -> repo/ -> copico/
_COPICO_ROOT = os.path.normpath(
    os.path.join(os.path.dirname(os.path.abspath(__file__)), "../../../..")
)
_LWASM_SIBLING = os.path.join(_COPICO_ROOT, "lwtools-4.21", "lwasm", "lwasm")


def find_lwasm():
    """Resolve lwasm: PATH first, then sibling lwtools under copico/."""
    candidates = ["lwasm", _LWASM_SIBLING]
    for path in candidates:
        if path == "lwasm":
            try:
                subprocess.run(
                    [path, "--version"], capture_output=True, check=True
                )
                return path
            except (FileNotFoundError, subprocess.CalledProcessError):
                continue
        elif os.path.isfile(path) and os.access(path, os.X_OK):
            return path
    return None


def build():
    print(f"Building {ASM_FILE} with lwasm...")

    lwasm_path = find_lwasm()
    if not lwasm_path:
        print("Error: lwasm not found.")
        print("  Install lwtools (lwasm on PATH), or place lwtools-4.21 next to this repo:")
        print(f"    Expected: {_LWASM_SIBLING}")
        sys.exit(1)

    result = subprocess.run(
        [lwasm_path, "--format=raw", "-o", BIN_FILE, ASM_FILE],
        capture_output=True,
        text=True,
    )

    if result.returncode != 0:
        print("Build failed!")
        print(result.stderr)
        sys.exit(1)

    if not os.path.exists(BIN_FILE):
        print(f"Error: {BIN_FILE} was not generated.")
        sys.exit(1)

    print(f"Build successful. Generated {BIN_FILE}.")

    # Read the binary, pad to exactly 8192 bytes ($C000-$DFFF)
    with open(BIN_FILE, "rb") as f:
        binary_data = f.read()

    ROM_SIZE = 8192
    size = len(binary_data)
    print(f"Binary size (pre-pad): {size} bytes")

    if size > ROM_SIZE:
        print(f"ERROR: Binary ({size} bytes) exceeds 8KB ROM window!")
        sys.exit(1)

    # Pad to exactly 8KB with $FF (erased EPROM value)
    binary_data = bytearray(binary_data + b"\xFF" * (ROM_SIZE - len(binary_data)))

    # CoCo maps CPU $FFFE-$FFFF to the last two bytes of the 8K ROM image.
    # Mirror the Disk-BASIC-style entry vector at $C002 into that slot.
    if len(binary_data) >= 4:
        binary_data[0x1FFE] = binary_data[2]
        binary_data[0x1FFF] = binary_data[3]
    binary_data = bytes(binary_data)
    size = ROM_SIZE
    print(f"Binary size (padded):  {size} bytes")

    # Write padded binary back out
    with open(BIN_FILE, "wb") as f:
        f.write(binary_data)

    print(f"Generating {HEADER_FILE}...")

    with open(HEADER_FILE, "w") as f:
        f.write(
            f"// Auto-generated by build_bios.py on "
            f"{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n"
        )
        f.write(f"// Source: {ASM_FILE}\n")
        f.write(f"// Size: {size} bytes\n\n")
        f.write("#ifndef XBIOS_ROM_H\n")
        f.write("#define XBIOS_ROM_H\n\n")
        f.write("#include <stdint.h>\n\n")

        f.write(f"const uint32_t {ARRAY_NAME}_len = {size};\n")
        f.write(f"const uint8_t {ARRAY_NAME}[] = {{\n")

        for i, byte in enumerate(binary_data):
            if i % 12 == 0:
                f.write("    ")
            f.write(f"0x{byte:02X}, ")
            if i % 12 == 11:
                f.write("\n")

        if size % 12 != 0:
            f.write("\n")

        f.write("};\n\n")
        f.write("#endif // XBIOS_ROM_H\n")

    print("Done!")


if __name__ == "__main__":
    build()
