import os
import subprocess
import sys
from datetime import datetime

ASM_FILE = "chameleon.asm"
BIN_FILE = "chameleon.rom"
HEADER_FILE = "chameleon_rom.h"
ARRAY_NAME = "chameleon_bios_bin"

def build():
    print(f"Building {ASM_FILE} with lwasm...")
    
    # Run lwasm to generate a raw binary
    # --format=raw generates pure machine code without DECB headers
    lwasm_path = "lwasm"
    
    # Check if lwasm is available in system PATH
    try:
        subprocess.run([lwasm_path, "--version"], capture_output=True, check=True)
    except (FileNotFoundError, subprocess.CalledProcessError):
        # Fallback to the locally compiled one
        local_lwasm = "/Users/macbook/Documents/PlatformIO/Projects/copico/lwtools-4.21/lwasm/lwasm"
        if os.path.exists(local_lwasm):
            lwasm_path = local_lwasm
        else:
            print("Error: lwasm not found. Please install lwtools.")
            sys.exit(1)

    result = subprocess.run(
        [lwasm_path, "--format=raw", "-o", BIN_FILE, ASM_FILE],
        capture_output=True,
        text=True
    )
    
    if result.returncode != 0:
        print("Build failed!")
        print(result.stderr)
        sys.exit(1)
        
    if not os.path.exists(BIN_FILE):
        print(f"Error: {BIN_FILE} was not generated.")
        sys.exit(1)
        
    print(f"Build successful. Generated {BIN_FILE}.")
    
    # Read the binary, pad to exactly 8192 bytes ($C000-$DFFF)
    with open(BIN_FILE, "rb") as f:
        binary_data = f.read()

    ROM_SIZE = 8192
    size = len(binary_data)
    print(f"Binary size (pre-pad): {size} bytes")

    if size > ROM_SIZE:
        print(f"ERROR: Binary ({size} bytes) exceeds 8KB ROM window!")
        sys.exit(1)

    # Pad to exactly 8KB with $FF (erased EPROM value)
    binary_data = binary_data + b'\xFF' * (ROM_SIZE - size)
    size = ROM_SIZE
    print(f"Binary size (padded):  {size} bytes")

    # Write padded binary back out
    with open(BIN_FILE, "wb") as f:
        f.write(binary_data)

    if size > 8192:
        print("WARNING: Binary exceeds 8KB ($C000-$DFFF shadow space)!")
    
    print(f"Generating {HEADER_FILE}...")
    
    with open(HEADER_FILE, "w") as f:
        f.write(f"// Auto-generated by build_bios.py on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        f.write(f"// Source: {ASM_FILE}\n")
        f.write(f"// Size: {size} bytes\n\n")
        f.write("#ifndef CHAMELEON_ROM_H\n")
        f.write("#define CHAMELEON_ROM_H\n\n")
        f.write("#include <stdint.h>\n\n")
        
        f.write(f"const uint32_t {ARRAY_NAME}_len = {size};\n")
        f.write(f"const uint8_t {ARRAY_NAME}[] = {{\n")
        
        for i, byte in enumerate(binary_data):
            if i % 12 == 0:
                f.write("    ")
            f.write(f"0x{byte:02X}, ")
            if i % 12 == 11:
                f.write("\n")
                
        if size % 12 != 0:
            f.write("\n")
            
        f.write("};\n\n")
        f.write("#endif // CHAMELEON_ROM_H\n")
        
    print("Done!")

if __name__ == "__main__":
    build()
