[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2
framework = arduino
board_build.core = earlephilhower

; Increase CPU speed to 250MHz for high-speed bus sniffing
board_build.f_cpu = 250000000L

monitor_speed = 115200

build_flags = 
    -D CORE_DEBUG_LEVEL=5
