[platformio]
default_envs = rp2350

[env:rp2350]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2
framework = arduino
board_build.core = earlephilhower

; Increase CPU speed to 250MHz for high-speed bus sniffing
board_build.f_cpu = 250000000L

monitor_speed = 115200

build_flags = 
    -D CORE_DEBUG_LEVEL=5

build_src_filter = +<*> -<../src_esp32/>

[env:esp32c3_coprocessor]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
build_src_filter = +<../src_esp32/> -<*>
lib_deps =
    ModemEngine
    greiman/SdFat
