// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ----------------- //
// coco_sniffer_addr //
// ----------------- //

#define coco_sniffer_addr_wrap_target 0
#define coco_sniffer_addr_wrap 3
#define coco_sniffer_addr_pio_version 0

static const uint16_t coco_sniffer_addr_program_instructions[] = {
            //     .wrap_target
    0x2095, //  0: wait   1 gpio, 21
    0x4010, //  1: in     pins, 16
    0x8000, //  2: push   noblock
    0x2015, //  3: wait   0 gpio, 21
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program coco_sniffer_addr_program = {
    .instructions = coco_sniffer_addr_program_instructions,
    .length = 4,
    .origin = -1,
    .pio_version = coco_sniffer_addr_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x2
#endif
};

static inline pio_sm_config coco_sniffer_addr_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + coco_sniffer_addr_wrap_target, offset + coco_sniffer_addr_wrap);
    return c;
}
#endif

// ----------------- //
// coco_sniffer_data //
// ----------------- //

#define coco_sniffer_data_wrap_target 0
#define coco_sniffer_data_wrap 3
#define coco_sniffer_data_pio_version 0

static const uint16_t coco_sniffer_data_program_instructions[] = {
            //     .wrap_target
    0x2095, //  0: wait   1 gpio, 21
    0x4008, //  1: in     pins, 8
    0x8000, //  2: push   noblock
    0x2015, //  3: wait   0 gpio, 21
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program coco_sniffer_data_program = {
    .instructions = coco_sniffer_data_program_instructions,
    .length = 4,
    .origin = -1,
    .pio_version = coco_sniffer_data_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x2
#endif
};

static inline pio_sm_config coco_sniffer_data_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + coco_sniffer_data_wrap_target, offset + coco_sniffer_data_wrap);
    return c;
}
#endif

// ------------- //
// coco_bus_read //
// ------------- //

#define coco_bus_read_wrap_target 0
#define coco_bus_read_wrap 4
#define coco_bus_read_pio_version 0

static const uint16_t coco_bus_read_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block
    0x6088, //  1: out    pindirs, 8
    0x6008, //  2: out    pins, 8
    0x2015, //  3: wait   0 gpio, 21
    0xe080, //  4: set    pindirs, 0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program coco_bus_read_program = {
    .instructions = coco_bus_read_program_instructions,
    .length = 5,
    .origin = -1,
    .pio_version = coco_bus_read_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x2
#endif
};

static inline pio_sm_config coco_bus_read_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + coco_bus_read_wrap_target, offset + coco_bus_read_wrap);
    return c;
}
#endif

