// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --------- //
// vga_hsync //
// --------- //

#define vga_hsync_wrap_target 1
#define vga_hsync_wrap 8
#define vga_hsync_pio_version 0

static const uint16_t vga_hsync_program_instructions[] = {
    0x80a0, //  0: pull   block
            //     .wrap_target
    0xa027, //  1: mov    x, osr
    0x0042, //  2: jmp    x--, 2
    0xff00, //  3: set    pins, 0                [31]
    0xff00, //  4: set    pins, 0                [31]
    0xff00, //  5: set    pins, 0                [31]
    0xff01, //  6: set    pins, 1                [31]
    0xed01, //  7: set    pins, 1                [13]
    0xc100, //  8: irq    nowait 0               [1]
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program vga_hsync_program = {
    .instructions = vga_hsync_program_instructions,
    .length = 9,
    .origin = -1,
    .pio_version = vga_hsync_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config vga_hsync_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + vga_hsync_wrap_target, offset + vga_hsync_wrap);
    return c;
}
#endif

// --------- //
// vga_vsync //
// --------- //

#define vga_vsync_wrap_target 1
#define vga_vsync_wrap 13
#define vga_vsync_pio_version 0

static const uint16_t vga_vsync_program_instructions[] = {
    0x80a0, //  0: pull   block
            //     .wrap_target
    0xa027, //  1: mov    x, osr
    0x20c0, //  2: wait   1 irq, 0
    0xc001, //  3: irq    nowait 1
    0x0042, //  4: jmp    x--, 2
    0xe049, //  5: set    y, 9
    0x20c0, //  6: wait   1 irq, 0
    0x0086, //  7: jmp    y--, 6
    0xe000, //  8: set    pins, 0
    0x20c0, //  9: wait   1 irq, 0
    0x20c0, // 10: wait   1 irq, 0
    0xe05f, // 11: set    y, 31
    0x38c0, // 12: wait   1 irq, 0        side 1
    0x008c, // 13: jmp    y--, 12
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program vga_vsync_program = {
    .instructions = vga_vsync_program_instructions,
    .length = 14,
    .origin = -1,
    .pio_version = vga_vsync_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config vga_vsync_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + vga_vsync_wrap_target, offset + vga_vsync_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}
#endif

// ------- //
// vga_rgb //
// ------- //

#define vga_rgb_wrap_target 2
#define vga_rgb_wrap 6
#define vga_rgb_pio_version 0

static const uint16_t vga_rgb_program_instructions[] = {
    0x80a0, //  0: pull   block           side 0
    0xa047, //  1: mov    y, osr          side 0
            //     .wrap_target
    0xa022, //  2: mov    x, y            side 0
    0xe000, //  3: set    pins, 0         side 0
    0x20c1, //  4: wait   1 irq, 1        side 0
    0x60f0, //  5: out    exec, 16        side 0
    0x0045, //  6: jmp    x--, 5          side 0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program vga_rgb_program = {
    .instructions = vga_rgb_program_instructions,
    .length = 7,
    .origin = -1,
    .pio_version = vga_rgb_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config vga_rgb_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + vga_rgb_wrap_target, offset + vga_rgb_wrap);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}
#endif

